### ISSUE TITLE
.to_json raising "undefined method `merge' for []:Array" in rails 3.1

### ISSUE THREAD

**Issue by pcboy** [SebastianEdwards/collection-json#1]
Hi,

I'm not sure it's a collection-json bug or a rails one.

When I try to convert my collection to json it raises undefined method `merge' for []:Array.
I've managed to find that the problem is in the .to_json method of the CollectionJSON::Attribute class. More precisely with the args argument.

If I convert this:

``` ruby
    def to_json(*args)
      to_hash.to_json(args)                                                       
    end
```

To this:

``` ruby
    def to_json(*args)
      to_hash.to_json
    end
```

No more problems.
At the same time, if I'm calling JSON.generate(collection.to_hash) in my code instead of collection.to_json it's working without any problem.
collection.to_json is working great in irb.
So I suppose there is a monkey patch clash somewhere with Rails.

Thanks

EDIT:
Looking more in depth into it, the optional parameter to to_json must be hash-like. You are using a splat so here it's an array and it fails.

Converting the .to_json method to something like that fixed the problem in rails:

``` ruby
    def to_json(args = {})
      to_hash.to_json(args)
    end
```

**Comment by SebastianEdwards** [comment]
Thanks for pointing this out. Looks like I wasn't passing the splat through properly. Have now updated the repo and pushed out a new gem which should fix the issue. Let me know if you have any further trouble though.

Also, thanks for being the first living, breathing evidence of someone using this gem. This is the first real open source project I've put out there so it's really cool to see someone playing with it. :)
